files:
  - source: "/Essentials/src/messages.properties"
    translation: "/Essentials/src/messages_%locale_with_underscore%.properties"
    languages_mapping:
      locale_with_underscore:
        cs-CZ: cs
        da-DK: da
        de-DE: de
        el-GR: el
        en-US: en
        es-ES: es
        fi-FI: fi
        fr-FR: fr
        hu-HU: hu
        it-IT: it
        ko-KR: ko
        nl-NL: nl
        no-NO: "no" # no is a YAML keyword
        pl-PL: pl
        pt-PT: pt
        ro-RO: ro
        ru-RU: ru
        sr-SP: sr
        sv-SE: sv
        tr-TR: tr
        uk-UA: uk
        vi-VN: vi
        zh-CN: zh
